# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:17
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadout', models.CharField(max_length=60)),
                ('can_kill', models.ManyToManyField(related_name='_soldier_can_kill_+', to='ass_brea_snip.Soldier')),
            ],
        ),
        migrations.CreateModel(
            name='SoldierLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='ass_brea_snip.Soldier')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', django.contrib.postgres.fields.jsonb.JSONField()),
                ('salt', django.contrib.postgres.fields.hstore.HStoreField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamer_tag', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abs_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='strategy',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ass_brea_snip.UserProfile'),
        ),
        migrations.AddField(
            model_name='soldierlevel',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldiers', to='ass_brea_snip.UserProfile'),
        ),
        migrations.AddField(
            model_name='match',
            name='blackbriar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackbriar_matches', to='ass_brea_snip.Strategy'),
        ),
        migrations.AddField(
            model_name='match',
            name='hitmen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitmen_matches', to='ass_brea_snip.Strategy'),
        ),
        migrations.AlterUniqueTogether(
            name='soldierlevel',
            unique_together=set([('soldier', 'user_profile')]),
        ),
    ]
