# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_brea_snip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='can_kill',
            field=models.ManyToManyField(related_name='killed_by', to='ass_brea_snip.Soldier'),
        ),
    ]
