# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_brea_snip', '0002_auto_20160320_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('challengee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenged', to='ass_brea_snip.UserProfile')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='ass_brea_snip.UserProfile')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ass_brea_snip.Match')),
            ],
        ),
    ]
