# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_brea_snip', '0002_auto_20160320_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='blackbriar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackbriar_matches', to='ass_brea_snip.Strategy'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hitmen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hitmen_matches', to='ass_brea_snip.Strategy'),
        ),
    ]
