# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 12:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_brea_snip', '0004_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='bio',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'icon_class': 'md-album'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='state',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
